version: '3.8'

# Load environment variables from environment.env file
# Copy environment.env to .env and customize before running
services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: timesheet-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-timesheet123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-timesheet_db}
      MYSQL_USER: ${MYSQL_USER:-timesheet_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-timesheet123}
    ports:
      - "0.0.0.0:${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    networks:
      - timesheet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 30s
      interval: 30s

  # Timesheet Application
  timesheet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet-app
    restart: unless-stopped
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-timesheet_db}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-timesheet_user}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-timesheet123}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-mysecretkey12345678901234567890123456789012345678901234567890}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      APP_JWT_SECRET: ${APP_JWT_SECRET:-mySecretKey}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS:-3600000}
      APP_JWT_REFRESH_EXPIRATION_MS: ${APP_JWT_REFRESH_EXPIRATION_MS:-86400000}
      
      # Application Configuration
      SERVER_PORT: 8080
      APP_FRONTEND_URL: ${APP_FRONTEND_URL:-http://0.0.0.0:8080}
      APP_INVOICE_UPLOAD_DIR: ./uploads/invoices
      APP_NAME: ${APP_NAME:-Timesheet Application}
      
      # File Upload Configuration
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      
      # API Configuration
      HOLIDAYS_API_SWEDEN_URL: https://api.dryg.net/dagar/v2.1/
      
      # Email Configuration (update with your SMTP settings)
      SPRING_MAIL_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SMTP_PORT:-587}
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME:-your-email@gmail.com}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD:-your-app-password}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_CONTINUE_ON_ERROR: true
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      
      # Logging Configuration
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      LOGGING_LEVEL_COM_EXAMPLE_TIMESHEET: INFO
      
      # Static Content Configuration
      SPRING_MVC_STATIC_PATH_PATTERN: /**
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: classpath:/static/
      SPRING_WEB_RESOURCES_CACHE_PERIOD: 3600
      SPRING_MVC_PATHMATCH_MATCHING_STRATEGY: ant_path_matcher
      
    ports:
      - "0.0.0.0:${APP_PORT:-8080}:8080"
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    networks:
      - timesheet-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health", "||", "exit", "1"]
      timeout: 10s
      retries: 5
      start_period: 60s
      interval: 30s

volumes:
  mysql_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local

networks:
  timesheet-network:
    driver: bridge
